写出导入numpy的语句，并且给numpy别名为np

In [1]:
import numpy as np

创建一个变量名为arr1的一维数组，里面元素为整数6，2，-7，8，-2，1。创建后输出arr1。

In [7]:
arr1=np.array([6,2,-7,8,-2,1])
print(arr1)

[ 6  2 -7  8 -2  1]


创建一个变量名为arr2的二维数组，里面的元素为以下两个数组：由整数1，3，5组成的一维数组，以及由整数2，4，6组成的一位数组，创建后输出

In [5]:
arr2=np.array([[1,3,5],[2,4,6]])
print(arr2)

[[1 3 5]
 [2 4 6]]


分别打印arr1和arr2的维度、形状、元素数量、元素类型。

In [12]:
print(arr1.ndim)
print(arr2.ndim)
print(arr1.shape)
print(arr2.shape)
print(arr1.size)
print(arr2.size)
print(arr1.dtype)

1
2
(6,)
(2, 3)
6
6
int64


创建一个变量名为arr_all_0的一维数组，里面的元素为6个0

arr_all_0 = np.zeros(6)
arr_all_0

创建一个变量名为arr_all_1的一维数组，里面元素为6个1

In [15]:
arr_all_1 = np.ones(6)
arr_all_1

array([1., 1., 1., 1., 1., 1.])

创建一个变量名为arr_even的一维数组，里面的元素为10（包括10）到20（包括20）之间的偶数，并输出

In [16]:
arr_even = np.arange(10,21,2)
arr_even

array([10, 12, 14, 16, 18, 20])

导入numpy

In [1]:
import numpy as np

创建arr1为包含元素1，3，2，4，9的数组，创建arr2为长度为5的由1组成的一维数组，arr3为长度为3的由0组成的数组

In [4]:
arr1 = np.array([1,3,2,4,9])
arr2 = np.ones(5)
arr3 = np.zeros(3)
print(arr1)
print(arr2)
print(arr3)

[1 3 2 4 9]
[1. 1. 1. 1. 1.]
[0. 0. 0.]


创建数组arr4,包括所有arr1,arr2,arr3里面的数字，并输出。

In [6]:
arr4 = np.concatenate([arr1,arr2,arr3])
arr4

array([1., 3., 2., 4., 9., 1., 1., 1., 1., 1., 0., 0., 0.])

更改arr1，对arr1里的元素进行排序，并输出排序后的结果。

In [7]:
arr1.sort()
arr1

array([1, 2, 3, 4, 9])

用两种方法打印arr1的第三个元素

In [8]:
print(arr1[2])
print(arr1[-3])

3
3


输出从arr1第2个元素到第4个元素组成的数组

In [9]:
print(arr1[1:4])

[2 3 4]


输出arr1与arr2的同位置元素相加后组成的数组

In [10]:
arr1+arr2

array([ 2.,  3.,  4.,  5., 10.])

输出arr1的各个元素乘以-5后组成的数组

In [11]:
arr1 * -5 

array([ -5, -10, -15, -20, -45])

打印arr1数组的最大值，最小值，和，平均值。

In [12]:
print(arr1.max())
print(arr1.min())
print(arr1.sum())
print(arr1.mean())

9
1
19
3.8


筛选出arr1数组里所有小于1或大于3的数字，并打印出来。

In [17]:
arr1[(arr1<1)|(arr1>3)]

array([4, 9])